version: '3'
services:
  openldap:
    image: osixia/openldap:1.2.4
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Mlstr"
      LDAP_DOMAIN: "mlstr.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "4dm1n"
      LDAP_CONFIG_PASSWORD: "C0nf1g"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
    tty: true
    stdin_open: true
    ports:
      - "389:389"
      - "636:636"
    domainname: "mlstr.org" # important: same as hostname
    hostname: "mlstr.org"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "9999:80"
    depends_on:
      - openldap
